config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :listings
  resources :conversations do
    resources :messages
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'listings#index'

  get '/support' => 'support#new'
  post '/support' => 'support#create'

  post '/bookings' => 'bookings#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :listing
    belongs_to :guest
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
    belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
    belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'
    belongs_to :listing
    
    has_many :messages, dependent: :destroy
    
    # validates_uniqueness_of :listing_id
    validates_uniqueness_of :sender_id, :scope => [:recipient_id, :listing_id]
    
    # scope :between, -> (sender_id, recipient_id) do
    #     where("(conversations.sender_id = ? AND conversations.recipient_id = ?) OR (conversations.sender_id = ? AND conversations.recipient_id = ?)", sender_id, recipient_id, recipient_id, sender_id)
    # end

    scope :between, -> (sender_id, recipient_id, listing_id) do
        where("(conversations.sender_id = ? AND conversations.recipient_id = ? AND conversations.listing_id = ?) OR (conversations.sender_id = ? AND conversations.recipient_id = ? AND conversations.listing_id = ?)", sender_id, recipient_id, listing_id, recipient_id, sender_id, listing_id)
    end
end

app/models/listing.rb
class Listing < ApplicationRecord
    include ImageUploader::Attachment.new(:image) # adds an `image` virtual attribute

    geocoded_by :full_address
    after_validation :geocode

    has_many :conversations, dependent: :destroy
    belongs_to :host, :foreign_key => :host_id, class_name: 'User'

    def full_address
        "#{street_address}, #{city}, #{ISO3166::Country.new(country_code.upcase).name}"
    end

end

app/models/message.rb
class Message < ActiveRecord::Base
    belongs_to :conversation
    belongs_to :user
    
    validates_presence_of :body, :conversation_id, :user_id
    
    def message_time
        created_at.strftime("%m/%d/%y at %l:%M %p")
    end
end

app/models/messages.rb
class Message < ActiveRecord::Base
    belongs_to :conversation
    belongs_to :user
    
    validates_presence_of :body, :conversation_id, :user_id
    
    def message_time
        created_at.strftime("%m/%d/%y at %l:%M %p")
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    def create
    end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @users = User.all
        @conversations = Conversation.all
    end

    def create
        if Conversation.between(params[:sender_id], params[:recipient_id], params[:listing_id]).present?
            @conversation = Conversation.between(params[:sender_id], params[:recipient_id], params[:listing_id]).first
        else
            @conversation = Conversation.create!(conversation_params)
        end
        redirect_to conversation_messages_path(@conversation)
    end

    private

    def conversation_params
        params.permit(:sender_id, :recipient_id, :listing_id)
    end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @conversation = Conversation.new

    @new_booking = Booking.new
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.host_id = current_user

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:title, :street_address, :city, :country_code, :bed_count, :bedroom_count, :bathroom_count, :description, :night_fee_cents, :cleaning_fee_cents, :image)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :set_conversation

    def index
        @messages = @conversation.messages
        
        if @messages.length > 10
            @over_ten = true
            @messages = @messages[-10..-1]
        end

        if params[:m]
            @over_ten = false
            @messages = @conversation.messages
        end

        if @messages.last
            if @messages.last.user_id != current_user.id
                @messages.last.read = true;
            end
        end

        @message = @conversation.messages.new
    end

    def new
        @message = @conversation.messages.new
    end

    def create
        @message = @conversation.messages.new(message_params)

        if @message.save
            redirect_to conversation_messages_path(@conversation)
        end
    end

    private

    def set_conversation
        @conversation = Conversation.find(params[:conversation_id])
    end

    def message_params
        params.require(:message).permit(:body, :user_id)
    end
end

app/controllers/support_controller.rb
class SupportController < ApplicationController
    def new
        @error_messages = []
    end

    def create
        from_email = params[:email]
        message = params[:message]

        @error_messages = []
        @error_messages << "Please enter email" if from_email.blank?
        @error_messages << "Please enter a message" if message.blank?

        if @error_messages.empty?
            SupportMailer.contact_support(from_email, message).deliver_now
            render :success
        else
            render :new
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def pluralize_without_count(count, noun)
        if count != 0
          count == 1 ? "#{noun}" : "#{noun.pluralize}"
        end
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
    def format_address(address, city, country)
        "#{address}, #{city}, #{ISO3166::Country.new(country.upcase)}"
    end

    def format_coordinates(latitude, longitude)
        "#{latitude},#{longitude}"
    end

    def format_cents(cents, country)
        Money.new(cents, ISO3166::Country.new(country.upcase).currency.iso_code).format
    end
end

app/helpers/support_helper.rb
module SupportHelper
end

app/views/conversations/index.html.erb
<h1>Mailbox</h1>
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
    <div class="collapse navbar-collapse">
        <div class="navbar-nav">
            <%= link_to "Home", root_path, class:"nav-item nav-link active" %>
            <%= link_to "Mailbox", conversations_path, class:"nav-item nav-link active" %>
        </div>
    </div>
</nav>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3"><h3>Delete</h3></div>
        <div class="col-sm-3"><h3>Subject</h3></div>
        <div class="col-sm-3"><h3>Sent To</h3></div>
        <div class="col-sm-3"><h3>Sent To</h3></div>
        <% @conversations.each do |conversation| %>
            <% if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>
                <% if conversation.sender_id == current_user.id %>
                    <% recipient = User.find(conversation.recipient_id) %>
                <% else %>
                    <% recipient = User.find(conversation.sender_id) %>
                <% end %>
                <div class="col-sm-3"><p>Delete</p></div>
                <div class="col-sm-3"><p><%= link_to "#{Listing.find(conversation.listing_id).title}", conversation_messages_path(conversation), class:"btn btn-primary" %></p></div>
                <div class="col-sm-3"><p><%= recipient.email %></p></div>
                <div class="col-sm-3"><p><%= conversation.messages.last.message_time %></p></div>
            <% end %>
        <% end %>
        </div>
    </div>
</div>

<%= link_to 'Back', listings_path, class: "btn btn-primary"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :listing_title %>
  </div>

  <div class="field">
    <% if @listing.image.present? %>
      <%= image_tag @listing.image_url %>
    <% end %>

    <%= form.label :image %>
    <%= form.hidden_field :image, value: @listing.cached_image_data %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :street_address %>
    <%= form.text_field :street_address, id: :listing_street_address %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :listing_city %>
  </div>

  <div class="field">
    <%= form.label :country_code %>
    <%= form.text_field :country_code, id: :listing_country_code %>
  </div>

  <div class="field">
    <%= form.label :bed_count %>
    <%= form.number_field :bed_count, id: :listing_bed_count %>
  </div>

  <div class="field">
    <%= form.label :bedroom_count %>
    <%= form.number_field :bedroom_count, id: :listing_bedroom_count %>
  </div>

  <div class="field">
    <%= form.label :bathroom_count %>
    <%= form.number_field :bathroom_count, id: :listing_bathroom_count %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :listing_description %>
  </div>

  <div class="field">
    <%= form.label :night_fee_cents %>
    <%= form.number_field :night_fee_cents, id: :listing_night_fee_cents %>
  </div>

  <div class="field">
    <%= form.label :cleaning_fee_cents %>
    <%= form.number_field :cleaning_fee_cents, id: :listing_cleaning_fee_cents %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings</h1>

<% if user_signed_in? %>
    <%= link_to 'New Listing', new_listing_path, class: "btn btn-primary " %>
    <%= link_to 'Mailbox', conversations_path, class:"btn btn-primary" %>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "btn btn-primary" %>
<% else %>
    <%= link_to 'Login', new_user_session_path, class: "btn btn-primary" %>
<% end %>

<br>

<div class="d-flex flex-wrap">
    <% @listings.each do |listing| %>
        <div class="p-2">
            <div class="card" style="width: 20rem;">
                <h4 class="card-header text-center"><%= listing.title %></h4>
                <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?center=#{listing.latitude},#{listing.longitude}&zoom=12&size=600x400", class: "card-img-top" %>
                <div class="card-block card-body">
                    <p class="card-text">
                        <strong>Address:</strong> <%= format_address(listing.street_address, listing.city, listing.country_code) %><br>
                        <strong><%= pluralize_without_count(listing.bedroom_count, 'Bedroom') %>:</strong> <%= listing.bedroom_count %><br>
                        <strong><%= pluralize_without_count(listing.bed_count, 'Bed') %>:</strong> <%= listing.bed_count %><br>
                        <strong><%= pluralize_without_count(listing.bathroom_count, 'Bathroom') %>:</strong> <%= listing.bathroom_count %><br>
                        <strong>Night Fee:</strong> <%= format_cents(listing.night_fee_cents, listing.country_code) %><br>
                        <strong>Cleaning Fee:</strong> <%= format_cents(listing.cleaning_fee_cents, listing.country_code) %>    
                    </p>
                    <details>
                        <summary>Photos</summary>
                        <% if listing.image.present? %>
                            <%= image_tag listing.image_url %>
                        <% end %>
                    </details><br>
                </div>
            <%= link_to 'Show', listing_path(listing), class:"btn btn-primary"%>
            </div>
        </div>
    <% end %>
</div>

<%= link_to 'Contact Support', support_path, class:"btn btn-primary" %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @listing.title %>
</p>

<p>
  <strong>Address:</strong>
  <%= format_address(@listing.street_address, @listing.city, @listing.country_code) %>
</p>

<p>
  <% if @listing.image.present? %>
      <%= image_tag @listing.image_url %>
  <% end %>
</p>

<p>
  <strong>Coordinates:</strong>
  <%= format_coordinates(@listing.latitude, @listing.longitude) %>
</p>

<p>
  <strong>Bedroom:</strong>
  <%= @listing.bedroom_count %>
</p>

<p>
  <strong>Bed:</strong>
  <%= @listing.bed_count %>
</p>

<p>
  <strong>Bathroom</strong>
  <%= @listing.bathroom_count %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<h2>Book</h2>
<p>
  <strong>Night Fee:</strong> <%= format_cents(@listing.night_fee_cents, @listing.country_code) %> per night
</p>
<p>
  <strong>Cleaning Fee:</strong> <%= format_cents(@listing.cleaning_fee_cents, @listing.country_code) %> per night
</p>

<%= form_with(model: @new_booking) do |f| %>
  <div>
    <%= f.label :check_in_at, 'Check In' %>
    <%= f.date_field :check_in_at %>
  </div>
  <div>
    <%= f.label :check_out_at, 'Check Out' %>
    <%= f.date_field :check_out_at %>
  </div>
  <div>
    <%= f.label :guest_count, 'Guests' %>
    <%= f.number_field :guest_count %>
  </div>
  <%= f.submit %>
<% end %>

<%= link_to 'Back', listings_path, class: "btn btn-primary"%>
<% if user_signed_in? %>
  <% if @listing.host_id == current_user.id %>
    <%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-primary" %>
    <%= link_to 'Delete', listing_path(@listing), method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-danger" %>
  <% else %>
    <%= link_to 'Message me', conversations_path(sender_id: current_user.id, recipient_id: @listing.host_id), method: 'post', class:"btn btn-primary" %>
  <% end %>
<% end %>

app/views/messages/index.html.erb
<div>
    Messaging <%= @conversation.listing.host.email %> regarding <strong><%=  @conversation.listing.title %></strong>
</div><br>

<div>
<% if @over_ten %>
    <%= link_to 'Show Previous', '?m=all' %>
<% end %>

<div class="ui segment">
    <% @messages.each do |message| %>
        <% if message.body %>
            <% user = User.find(message.user_id) %>
            <div class="item">
                <div class="content">
                    <div class="header"><strong><%= user.email %></strong> <%= message.message_time %></div>
                    <div class="list">
                        <div class="item">
                            <i class="right triangle icon"></i>
                            <%= message.body %>
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    <% end %>
</div>

<%= form_with(model: [@conversation, @message], html: {class: "ui reply form"}) do |f| %>
    <div class="field">
        <%= f.text_area :body, class: "form-control" %>
    </div>
        <%= f.text_field :user_id, value: current_user.id, type: "hidden" %>
    <div>
        <%= f.submit "Add Reply", class: "ui blue labeled submit icon button" %>
    </div>
<% end %><br>

<%= link_to "Back", conversations_path, class:'btn btn-primary' %>
</div>

app/views/support/new.html.erb
<%= form_with(url: support_url, local: true) do |f| %>

    <% unless @error_messages.empty? %>
        <% @error_messages.each do |message| %>
            <p><%= message %></p>
        <% end %>
    <% end %>

    <div>
        <%= f.label :email %>
        <%= f.email_field :email %>
    </div>
    <div>
        <%= f.label :message %>
        <%= f.text_area :message, rows: 6 %>
    </div>
    <%= f.submit "Send" %>
<% end %>

app/views/support/success.html.erb
<p>Your message has been successfully been received</p>